name: hyperion
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip=23.0
  - pip:
    - torch==2.3.0+rocm6.2.0 --index-url https://download.pytorch.org/whl/rocm6.2.0
    - numpy==1.26.4  # Specific version to avoid compatibility issues with numpy 2.0
    - matplotlib
    - pandas
    - tqdm
    - tabulate
    - jupyter
    - jupyterlab==4.2.5
